### PR TITLE
Fix show errors mode being ignored by checkstyle output, fixes #262

### LINKED ISSUE #262: Checkstyle mode ignores show only errors

### PR DESCRIPTION
**Pull request by nl5887**

### CODE REVIEW

File: checkstyle.go [hunk 1]
```diff
@@ -42,6 +42,13 @@ func outputToCheckstyle(issues chan *Issue) int {
 				Name: issue.Path,
 			}
 		}
+
+		if !config.Errors {
+		} else if issue.Severity == Error {
+		} else {
+			continue
+		}
```
Comment (alecthomas) [inline checkstyle.go]: Can you simplify this into one expression please?

```go
if config.Errors && issue.Severity != Error {
  continue
}
```

**Comment by alecthomas** [comment]
Thanks!

**Comment by JackTiger** [comment]
@nl5887 @alecthomas CheckStyle Plugin can not show source from the check result from gometalinter
#283
